<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vhu/v1/definitions.proto

namespace App\Services\VHU;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Static Content pages from the website
 *
 * Generated from protobuf message <code>vhu.v1.ContentPage</code>
 */
class ContentPage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string staticcontent = 1 [json_name = "staticcontent"];</code>
     */
    protected $staticcontent = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $staticcontent
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vhu\V1\Definitions::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string staticcontent = 1 [json_name = "staticcontent"];</code>
     * @return string
     */
    public function getStaticcontent()
    {
        return $this->staticcontent;
    }

    /**
     * Generated from protobuf field <code>string staticcontent = 1 [json_name = "staticcontent"];</code>
     * @param string $var
     * @return $this
     */
    public function setStaticcontent($var)
    {
        GPBUtil::checkString($var, True);
        $this->staticcontent = $var;

        return $this;
    }

}

