<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vhu/v1/services.proto

namespace App\Services\VHU;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vhu.v1.GetTimelineResponse</code>
 */
class GetTimelineResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.vhu.v1.Timeline timeline = 1 [json_name = "timeline"];</code>
     */
    protected $timeline = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Services\VHU\Timeline $timeline
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vhu\V1\Services::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.vhu.v1.Timeline timeline = 1 [json_name = "timeline"];</code>
     * @return \App\Services\VHU\Timeline|null
     */
    public function getTimeline()
    {
        return $this->timeline;
    }

    public function hasTimeline()
    {
        return isset($this->timeline);
    }

    public function clearTimeline()
    {
        unset($this->timeline);
    }

    /**
     * Generated from protobuf field <code>.vhu.v1.Timeline timeline = 1 [json_name = "timeline"];</code>
     * @param \App\Services\VHU\Timeline $var
     * @return $this
     */
    public function setTimeline($var)
    {
        GPBUtil::checkMessage($var, \App\Services\VHU\Timeline::class);
        $this->timeline = $var;

        return $this;
    }

}

