<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vhu/v1/services.proto

namespace App\Services\VHU;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vhu.v1.ListTimelinesResponse</code>
 */
class ListTimelinesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .vhu.v1.ListTimelineResponseEntry timelines = 1 [json_name = "timelines"];</code>
     */
    private $timelines;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\App\Services\VHU\ListTimelineResponseEntry>|\Google\Protobuf\Internal\RepeatedField $timelines
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vhu\V1\Services::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.ListTimelineResponseEntry timelines = 1 [json_name = "timelines"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTimelines()
    {
        return $this->timelines;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.ListTimelineResponseEntry timelines = 1 [json_name = "timelines"];</code>
     * @param array<\App\Services\VHU\ListTimelineResponseEntry>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTimelines($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Services\VHU\ListTimelineResponseEntry::class);
        $this->timelines = $arr;

        return $this;
    }

}

