<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vhu/v1/definitions.proto

namespace App\Services\VHU;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vhu.v1.Metadata</code>
 */
class Metadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string object_number = 1 [json_name = "objectNumber"];</code>
     */
    protected $object_number = '';
    /**
     * Generated from protobuf field <code>string object_date = 2 [json_name = "objectDate"];</code>
     */
    protected $object_date = '';
    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Measurement measurements = 3 [json_name = "measurements"];</code>
     */
    private $measurements;
    /**
     * Generated from protobuf field <code>string documentation = 4 [json_name = "documentation"];</code>
     */
    protected $documentation = '';
    /**
     * Generated from protobuf field <code>string association = 5 [json_name = "association"];</code>
     */
    protected $association = '';
    /**
     * Generated from protobuf field <code>repeated string object_type = 6 [json_name = "objectType"];</code>
     */
    private $object_type;
    /**
     * Generated from protobuf field <code>string rights = 7 [json_name = "rights"];</code>
     */
    protected $rights = '';
    /**
     * Generated from protobuf field <code>repeated string creators = 9 [json_name = "creators"];</code>
     */
    private $creators;
    /**
     * Generated from protobuf field <code>repeated string subject = 10 [json_name = "subject"];</code>
     */
    private $subject;
    /**
     * Generated from protobuf field <code>repeated string dimensions = 12 [json_name = "dimensions"];</code>
     */
    private $dimensions;
    /**
     * Generated from protobuf field <code>repeated string material = 13 [json_name = "material"];</code>
     */
    private $material;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $object_number
     *     @type string $object_date
     *     @type array<\App\Services\VHU\Measurement>|\Google\Protobuf\Internal\RepeatedField $measurements
     *     @type string $documentation
     *     @type string $association
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $object_type
     *     @type string $rights
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $creators
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $subject
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $dimensions
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $material
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vhu\V1\Definitions::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string object_number = 1 [json_name = "objectNumber"];</code>
     * @return string
     */
    public function getObjectNumber()
    {
        return $this->object_number;
    }

    /**
     * Generated from protobuf field <code>string object_number = 1 [json_name = "objectNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setObjectNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->object_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string object_date = 2 [json_name = "objectDate"];</code>
     * @return string
     */
    public function getObjectDate()
    {
        return $this->object_date;
    }

    /**
     * Generated from protobuf field <code>string object_date = 2 [json_name = "objectDate"];</code>
     * @param string $var
     * @return $this
     */
    public function setObjectDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->object_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Measurement measurements = 3 [json_name = "measurements"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMeasurements()
    {
        return $this->measurements;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Measurement measurements = 3 [json_name = "measurements"];</code>
     * @param array<\App\Services\VHU\Measurement>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMeasurements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Services\VHU\Measurement::class);
        $this->measurements = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string documentation = 4 [json_name = "documentation"];</code>
     * @return string
     */
    public function getDocumentation()
    {
        return $this->documentation;
    }

    /**
     * Generated from protobuf field <code>string documentation = 4 [json_name = "documentation"];</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentation($var)
    {
        GPBUtil::checkString($var, True);
        $this->documentation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string association = 5 [json_name = "association"];</code>
     * @return string
     */
    public function getAssociation()
    {
        return $this->association;
    }

    /**
     * Generated from protobuf field <code>string association = 5 [json_name = "association"];</code>
     * @param string $var
     * @return $this
     */
    public function setAssociation($var)
    {
        GPBUtil::checkString($var, True);
        $this->association = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string object_type = 6 [json_name = "objectType"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getObjectType()
    {
        return $this->object_type;
    }

    /**
     * Generated from protobuf field <code>repeated string object_type = 6 [json_name = "objectType"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setObjectType($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->object_type = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rights = 7 [json_name = "rights"];</code>
     * @return string
     */
    public function getRights()
    {
        return $this->rights;
    }

    /**
     * Generated from protobuf field <code>string rights = 7 [json_name = "rights"];</code>
     * @param string $var
     * @return $this
     */
    public function setRights($var)
    {
        GPBUtil::checkString($var, True);
        $this->rights = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string creators = 9 [json_name = "creators"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCreators()
    {
        return $this->creators;
    }

    /**
     * Generated from protobuf field <code>repeated string creators = 9 [json_name = "creators"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCreators($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->creators = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string subject = 10 [json_name = "subject"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Generated from protobuf field <code>repeated string subject = 10 [json_name = "subject"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubject($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->subject = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string dimensions = 12 [json_name = "dimensions"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDimensions()
    {
        return $this->dimensions;
    }

    /**
     * Generated from protobuf field <code>repeated string dimensions = 12 [json_name = "dimensions"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDimensions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->dimensions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string material = 13 [json_name = "material"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMaterial()
    {
        return $this->material;
    }

    /**
     * Generated from protobuf field <code>repeated string material = 13 [json_name = "material"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMaterial($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->material = $arr;

        return $this;
    }

}

