<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vhu/v1/definitions.proto

namespace App\Services\VHU;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vhu.v1.Metadata</code>
 */
class Metadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string object_number = 1 [json_name = "objectNumber"];</code>
     */
    protected $object_number = '';
    /**
     * Generated from protobuf field <code>string object_date = 2 [json_name = "objectDate"];</code>
     */
    protected $object_date = '';
    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Measurement measurements = 3 [json_name = "measurements"];</code>
     */
    private $measurements;
    /**
     * Generated from protobuf field <code>string documentation = 4 [json_name = "documentation"];</code>
     */
    protected $documentation = '';
    /**
     * Generated from protobuf field <code>string association = 5 [json_name = "association"];</code>
     */
    protected $association = '';
    /**
     * Generated from protobuf field <code>string object_type = 6 [json_name = "objectType"];</code>
     */
    protected $object_type = '';
    /**
     * Generated from protobuf field <code>string rights = 7 [json_name = "rights"];</code>
     */
    protected $rights = '';
    /**
     * Generated from protobuf field <code>.vhu.v1.Theme theme = 8 [json_name = "theme"];</code>
     */
    protected $theme = null;
    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Person creators = 9 [json_name = "creators"];</code>
     */
    private $creators;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $object_number
     *     @type string $object_date
     *     @type array<\App\Services\VHU\Measurement>|\Google\Protobuf\Internal\RepeatedField $measurements
     *     @type string $documentation
     *     @type string $association
     *     @type string $object_type
     *     @type string $rights
     *     @type \App\Services\VHU\Theme $theme
     *     @type array<\App\Services\VHU\Person>|\Google\Protobuf\Internal\RepeatedField $creators
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vhu\V1\Definitions::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string object_number = 1 [json_name = "objectNumber"];</code>
     * @return string
     */
    public function getObjectNumber()
    {
        return $this->object_number;
    }

    /**
     * Generated from protobuf field <code>string object_number = 1 [json_name = "objectNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setObjectNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->object_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string object_date = 2 [json_name = "objectDate"];</code>
     * @return string
     */
    public function getObjectDate()
    {
        return $this->object_date;
    }

    /**
     * Generated from protobuf field <code>string object_date = 2 [json_name = "objectDate"];</code>
     * @param string $var
     * @return $this
     */
    public function setObjectDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->object_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Measurement measurements = 3 [json_name = "measurements"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMeasurements()
    {
        return $this->measurements;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Measurement measurements = 3 [json_name = "measurements"];</code>
     * @param array<\App\Services\VHU\Measurement>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMeasurements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Services\VHU\Measurement::class);
        $this->measurements = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string documentation = 4 [json_name = "documentation"];</code>
     * @return string
     */
    public function getDocumentation()
    {
        return $this->documentation;
    }

    /**
     * Generated from protobuf field <code>string documentation = 4 [json_name = "documentation"];</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentation($var)
    {
        GPBUtil::checkString($var, True);
        $this->documentation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string association = 5 [json_name = "association"];</code>
     * @return string
     */
    public function getAssociation()
    {
        return $this->association;
    }

    /**
     * Generated from protobuf field <code>string association = 5 [json_name = "association"];</code>
     * @param string $var
     * @return $this
     */
    public function setAssociation($var)
    {
        GPBUtil::checkString($var, True);
        $this->association = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string object_type = 6 [json_name = "objectType"];</code>
     * @return string
     */
    public function getObjectType()
    {
        return $this->object_type;
    }

    /**
     * Generated from protobuf field <code>string object_type = 6 [json_name = "objectType"];</code>
     * @param string $var
     * @return $this
     */
    public function setObjectType($var)
    {
        GPBUtil::checkString($var, True);
        $this->object_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rights = 7 [json_name = "rights"];</code>
     * @return string
     */
    public function getRights()
    {
        return $this->rights;
    }

    /**
     * Generated from protobuf field <code>string rights = 7 [json_name = "rights"];</code>
     * @param string $var
     * @return $this
     */
    public function setRights($var)
    {
        GPBUtil::checkString($var, True);
        $this->rights = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.vhu.v1.Theme theme = 8 [json_name = "theme"];</code>
     * @return \App\Services\VHU\Theme|null
     */
    public function getTheme()
    {
        return $this->theme;
    }

    public function hasTheme()
    {
        return isset($this->theme);
    }

    public function clearTheme()
    {
        unset($this->theme);
    }

    /**
     * Generated from protobuf field <code>.vhu.v1.Theme theme = 8 [json_name = "theme"];</code>
     * @param \App\Services\VHU\Theme $var
     * @return $this
     */
    public function setTheme($var)
    {
        GPBUtil::checkMessage($var, \App\Services\VHU\Theme::class);
        $this->theme = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Person creators = 9 [json_name = "creators"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCreators()
    {
        return $this->creators;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Person creators = 9 [json_name = "creators"];</code>
     * @param array<\App\Services\VHU\Person>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCreators($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Services\VHU\Person::class);
        $this->creators = $arr;

        return $this;
    }

}

