<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vhu/v1/definitions.proto

namespace App\Services\VHU;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vhu.v1.MuseumObjectInfo</code>
 */
class MuseumObjectInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string title = 1 [json_name = "title"];</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string image = 2 [json_name = "image"];</code>
     */
    protected $image = '';
    /**
     * Generated from protobuf field <code>string id = 3 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string uri = 4 [json_name = "uri"];</code>
     */
    protected $uri = '';
    /**
     * Generated from protobuf field <code>string object_number = 5 [json_name = "objectNumber"];</code>
     */
    protected $object_number = '';
    /**
     * Generated from protobuf field <code>string museum_name = 6 [json_name = "museumName"];</code>
     */
    protected $museum_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *     @type string $image
     *     @type string $id
     *     @type string $uri
     *     @type string $object_number
     *     @type string $museum_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vhu\V1\Definitions::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string title = 1 [json_name = "title"];</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 1 [json_name = "title"];</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string image = 2 [json_name = "image"];</code>
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Generated from protobuf field <code>string image = 2 [json_name = "image"];</code>
     * @param string $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->image = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string id = 3 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 3 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uri = 4 [json_name = "uri"];</code>
     * @return string
     */
    public function getUri()
    {
        return $this->uri;
    }

    /**
     * Generated from protobuf field <code>string uri = 4 [json_name = "uri"];</code>
     * @param string $var
     * @return $this
     */
    public function setUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->uri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string object_number = 5 [json_name = "objectNumber"];</code>
     * @return string
     */
    public function getObjectNumber()
    {
        return $this->object_number;
    }

    /**
     * Generated from protobuf field <code>string object_number = 5 [json_name = "objectNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setObjectNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->object_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string museum_name = 6 [json_name = "museumName"];</code>
     * @return string
     */
    public function getMuseumName()
    {
        return $this->museum_name;
    }

    /**
     * Generated from protobuf field <code>string museum_name = 6 [json_name = "museumName"];</code>
     * @param string $var
     * @return $this
     */
    public function setMuseumName($var)
    {
        GPBUtil::checkString($var, True);
        $this->museum_name = $var;

        return $this;
    }

}

