<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vhu/v1/definitions.proto

namespace App\Services\VHU;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vhu.v1.Relations</code>
 */
class Relations extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Collection collections = 2 [json_name = "collections"];</code>
     */
    private $collections;
    /**
     * Generated from protobuf field <code>repeated .vhu.v1.SubCollection sub_collections = 3 [json_name = "subCollections"];</code>
     */
    private $sub_collections;
    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Theme themes = 4 [json_name = "themes"];</code>
     */
    private $themes;
    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Event events = 5 [json_name = "events"];</code>
     */
    private $events;
    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Museum museums = 6 [json_name = "museums"];</code>
     */
    private $museums;
    /**
     * Generated from protobuf field <code>repeated .vhu.v1.ObjectRecord objects = 7 [json_name = "objects"];</code>
     */
    private $objects;
    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Person persons = 8 [json_name = "persons"];</code>
     */
    private $persons;
    /**
     * Generated from protobuf field <code>repeated .vhu.v1.StoryCard story_cards = 9 [json_name = "storyCards"];</code>
     */
    private $story_cards;
    /**
     * Generated from protobuf field <code>repeated .vhu.v1.LongRead long_reads = 10 [json_name = "longReads"];</code>
     */
    private $long_reads;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\App\Services\VHU\Collection>|\Google\Protobuf\Internal\RepeatedField $collections
     *     @type array<\App\Services\VHU\SubCollection>|\Google\Protobuf\Internal\RepeatedField $sub_collections
     *     @type array<\App\Services\VHU\Theme>|\Google\Protobuf\Internal\RepeatedField $themes
     *     @type array<\App\Services\VHU\Event>|\Google\Protobuf\Internal\RepeatedField $events
     *     @type array<\App\Services\VHU\Museum>|\Google\Protobuf\Internal\RepeatedField $museums
     *     @type array<\App\Services\VHU\ObjectRecord>|\Google\Protobuf\Internal\RepeatedField $objects
     *     @type array<\App\Services\VHU\Person>|\Google\Protobuf\Internal\RepeatedField $persons
     *     @type array<\App\Services\VHU\StoryCard>|\Google\Protobuf\Internal\RepeatedField $story_cards
     *     @type array<\App\Services\VHU\LongRead>|\Google\Protobuf\Internal\RepeatedField $long_reads
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vhu\V1\Definitions::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Collection collections = 2 [json_name = "collections"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCollections()
    {
        return $this->collections;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Collection collections = 2 [json_name = "collections"];</code>
     * @param array<\App\Services\VHU\Collection>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCollections($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Services\VHU\Collection::class);
        $this->collections = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.SubCollection sub_collections = 3 [json_name = "subCollections"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubCollections()
    {
        return $this->sub_collections;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.SubCollection sub_collections = 3 [json_name = "subCollections"];</code>
     * @param array<\App\Services\VHU\SubCollection>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubCollections($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Services\VHU\SubCollection::class);
        $this->sub_collections = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Theme themes = 4 [json_name = "themes"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getThemes()
    {
        return $this->themes;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Theme themes = 4 [json_name = "themes"];</code>
     * @param array<\App\Services\VHU\Theme>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setThemes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Services\VHU\Theme::class);
        $this->themes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Event events = 5 [json_name = "events"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Event events = 5 [json_name = "events"];</code>
     * @param array<\App\Services\VHU\Event>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Services\VHU\Event::class);
        $this->events = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Museum museums = 6 [json_name = "museums"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMuseums()
    {
        return $this->museums;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Museum museums = 6 [json_name = "museums"];</code>
     * @param array<\App\Services\VHU\Museum>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMuseums($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Services\VHU\Museum::class);
        $this->museums = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.ObjectRecord objects = 7 [json_name = "objects"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getObjects()
    {
        return $this->objects;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.ObjectRecord objects = 7 [json_name = "objects"];</code>
     * @param array<\App\Services\VHU\ObjectRecord>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setObjects($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Services\VHU\ObjectRecord::class);
        $this->objects = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Person persons = 8 [json_name = "persons"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPersons()
    {
        return $this->persons;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.Person persons = 8 [json_name = "persons"];</code>
     * @param array<\App\Services\VHU\Person>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPersons($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Services\VHU\Person::class);
        $this->persons = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.StoryCard story_cards = 9 [json_name = "storyCards"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStoryCards()
    {
        return $this->story_cards;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.StoryCard story_cards = 9 [json_name = "storyCards"];</code>
     * @param array<\App\Services\VHU\StoryCard>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStoryCards($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Services\VHU\StoryCard::class);
        $this->story_cards = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.LongRead long_reads = 10 [json_name = "longReads"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLongReads()
    {
        return $this->long_reads;
    }

    /**
     * Generated from protobuf field <code>repeated .vhu.v1.LongRead long_reads = 10 [json_name = "longReads"];</code>
     * @param array<\App\Services\VHU\LongRead>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLongReads($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Services\VHU\LongRead::class);
        $this->long_reads = $arr;

        return $this;
    }

}

