<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vhu/v1/definitions.proto

namespace App\Services\VHU;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vhu.v1.StoryCard</code>
 */
class StoryCard extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.vhu.v1.WebsiteContent content = 1 [json_name = "content"];</code>
     */
    protected $content = null;
    /**
     * Generated from protobuf field <code>.vhu.v1.Header header = 2 [json_name = "header"];</code>
     */
    protected $header = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Services\VHU\WebsiteContent $content
     *     @type \App\Services\VHU\Header $header
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vhu\V1\Definitions::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.vhu.v1.WebsiteContent content = 1 [json_name = "content"];</code>
     * @return \App\Services\VHU\WebsiteContent|null
     */
    public function getContent()
    {
        return $this->content;
    }

    public function hasContent()
    {
        return isset($this->content);
    }

    public function clearContent()
    {
        unset($this->content);
    }

    /**
     * Generated from protobuf field <code>.vhu.v1.WebsiteContent content = 1 [json_name = "content"];</code>
     * @param \App\Services\VHU\WebsiteContent $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkMessage($var, \App\Services\VHU\WebsiteContent::class);
        $this->content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.vhu.v1.Header header = 2 [json_name = "header"];</code>
     * @return \App\Services\VHU\Header|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.vhu.v1.Header header = 2 [json_name = "header"];</code>
     * @param \App\Services\VHU\Header $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \App\Services\VHU\Header::class);
        $this->header = $var;

        return $this;
    }

}

