<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vhu/v1/definitions.proto

namespace App\Services\VHU;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vhu.v1.ThesaurusConcept</code>
 */
class ThesaurusConcept extends \Google\Protobuf\Internal\Message
{
    /**
     * STT URI
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string pref_label = 2 [json_name = "prefLabel"];</code>
     */
    protected $pref_label = '';
    /**
     * Generated from protobuf field <code>string scope_notes = 3 [json_name = "scopeNotes"];</code>
     */
    protected $scope_notes = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           STT URI
     *     @type string $pref_label
     *     @type string $scope_notes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vhu\V1\Definitions::initOnce();
        parent::__construct($data);
    }

    /**
     * STT URI
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * STT URI
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pref_label = 2 [json_name = "prefLabel"];</code>
     * @return string
     */
    public function getPrefLabel()
    {
        return $this->pref_label;
    }

    /**
     * Generated from protobuf field <code>string pref_label = 2 [json_name = "prefLabel"];</code>
     * @param string $var
     * @return $this
     */
    public function setPrefLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->pref_label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string scope_notes = 3 [json_name = "scopeNotes"];</code>
     * @return string
     */
    public function getScopeNotes()
    {
        return $this->scope_notes;
    }

    /**
     * Generated from protobuf field <code>string scope_notes = 3 [json_name = "scopeNotes"];</code>
     * @param string $var
     * @return $this
     */
    public function setScopeNotes($var)
    {
        GPBUtil::checkString($var, True);
        $this->scope_notes = $var;

        return $this;
    }

}

