<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vhu/v1/definitions.proto

namespace GPBMetadata\Vhu\V1;

class Definitions
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ƒ
vhu/v1/definitions.protovhu.v1"£
Header
title (	Rtitle 
description (	Rdescription
summary (	Rsummary%
images (2.vhu.v1.ImageRimages
id (	Rid
uri (	Ruri"K
Image
uri (	Ruri
rights (	Rrights
caption (	Rcaption"Y
Timeline&
header (2.vhu.v1.HeaderRheader%
events (2.vhu.v1.EventRevents"‰
Event&
header (2.vhu.v1.HeaderRheader

start_date (	R	startDate
end_date (	RendDate
period (	Rperiod2
objects (2.vhu.v1.MuseumObjectInfoRobjects
is_group (RisGroup
year (	Ryear"À
MuseumObjectInfo
title (	Rtitle
image (	Rimage
id (	Rid
uri (	Ruri#
object_number (	RobjectNumber
museum_name (	R
museumName#
concept_label (	RconceptLabel"ã
MuseumObject&
header (2.vhu.v1.HeaderRheader,
metadata (2.vhu.v1.MetadataRmetadata4
concepts (2.vhu.v1.ThesaurusConceptRconcepts=
related_objects (2.vhu.v1.MuseumObjectRrelatedObjects0
	link_info (2.vhu.v1.ObjLinkInfoRlinkInfo"ç
ObjLinkInfo
museum_name (	R
museumName#
object_number (	RobjectNumber
object_name (	R
objectName
dcn_uri (	RdcnUri"¸
Metadata#
object_number (	RobjectNumber
object_date (	R
objectDate7
measurements (2.vhu.v1.MeasurementRmeasurements$
documentation (	Rdocumentation 
association (	Rassociation
object_type (	R
objectType
rights (	Rrights
creators	 (	Rcreators
subject
 (	Rsubject

dimensions (	R
dimensions
material (	Rmaterial"v
Measurement
height (Rheight
width (Rwidth
unit (	Runit%
dimension_type (	RdimensionType"b
ThesaurusConcept
id (	Rid

pref_label (	R	prefLabel
scope_notes (	R
scopeNotesBZpoc/vhu App\\Services\\VHUbproto3'
        , true);

        static::$is_initialized = true;
    }
}

