<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vhu/v1/services.proto

namespace GPBMetadata\Vhu\V1;

class Services
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Vhu\V1\Definitions::initOnce();
        $pool->internalAddGeneratedFile(
            '
õ
vhu/v1/services.protovhu.v1""
GetObjectRequest
id (	Rid"A
GetObjectResponse,
object (2.vhu.v1.ObjectRecordRobject">
ListObjectsRequest
query (	Rquery
page (Rpage"E
ListObjectsResponse.
objects (2.vhu.v1.ObjectRecordRobjects"$
GetTimelineRequest
id (	Rid"?
GetTimelineResponse(
object (2.vhu.v1.TimelineRobject2ü
ObjectRecordService@
	GetObject.vhu.v1.GetObjectRequest.vhu.v1.GetObjectResponseF
ListObjects.vhu.v1.ListObjectsRequest.vhu.v1.ListObjectsResponse2Y
TimelineServiceF
GetTimeline.vhu.v1.GetTimelineRequest.vhu.v1.GetTimelineResponseB Zdelving.vhu App\\Services\\VHUbproto3'
        , true);

        static::$is_initialized = true;
    }
}

