<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vhu/v1/services.proto

namespace GPBMetadata\Vhu\V1;

class Services
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Vhu\V1\Definitions::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ä
vhu/v1/services.protovhu.v1"$
GetTimelineRequest
id (	Rid"C
GetTimelineResponse,
timeline (2.vhu.v1.TimelineRtimeline"A
ListTimelineResponseEntry
id (	Rid
title (	Rtitle"
ListTimelinesRequest"X
ListTimelinesResponse?
	timelines (2!.vhu.v1.ListTimelineResponseEntryR	timelines"(
GetMuseumObjectRequest
id (	Rid"G
GetMuseumObjectResponse,
object (2.vhu.v1.MuseumObjectRobject"i
ListMuseumObjectsRequest
query (	Rquery
page (Rpage#
query_filters (	RqueryFilters"K
ListMuseumObjectsResponse.
objects (2.vhu.v1.MuseumObjectRobjects2ß
TimelineServiceF
GetTimeline.vhu.v1.GetTimelineRequest.vhu.v1.GetTimelineResponseL
ListTimelines.vhu.v1.ListTimelinesRequest.vhu.v1.ListTimelinesResponse2√
MuseumObjectServiceR
GetMuseumObject.vhu.v1.GetMuseumObjectRequest.vhu.v1.GetMuseumObjectResponseX
ListMuseumObjects .vhu.v1.ListMuseumObjectsRequest!.vhu.v1.ListMuseumObjectsResponseBZpoc/vhu App\\Services\\VHUbproto3'
        , true);

        static::$is_initialized = true;
    }
}

