// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: vhu/v1/definitions.proto

package vhu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Collection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Collection) Reset() {
	*x = Collection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{0}
}

// Static Content pages from the website
type ContentPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Staticcontent string `protobuf:"bytes,1,opt,name=staticcontent,proto3" json:"staticcontent,omitempty"`
}

func (x *ContentPage) Reset() {
	*x = ContentPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentPage) ProtoMessage() {}

func (x *ContentPage) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentPage.ProtoReflect.Descriptor instead.
func (*ContentPage) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{1}
}

func (x *ContentPage) GetStaticcontent() string {
	if x != nil {
		return x.Staticcontent
	}
	return ""
}

type DownloadLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri     string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Rights  string `protobuf:"bytes,2,opt,name=rights,proto3" json:"rights,omitempty"`
	Caption string `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
}

func (x *DownloadLink) Reset() {
	*x = DownloadLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadLink) ProtoMessage() {}

func (x *DownloadLink) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadLink.ProtoReflect.Descriptor instead.
func (*DownloadLink) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadLink) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *DownloadLink) GetRights() string {
	if x != nil {
		return x.Rights
	}
	return ""
}

func (x *DownloadLink) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{3}
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Summary     string   `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Images      []*Image `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{4}
}

func (x *Header) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Header) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Header) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Header) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri     string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Rights  string `protobuf:"bytes,2,opt,name=rights,proto3" json:"rights,omitempty"`
	Caption string `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{5}
}

func (x *Image) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Image) GetRights() string {
	if x != nil {
		return x.Rights
	}
	return ""
}

func (x *Image) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

type LongRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content *WebsiteContent `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Header  *Header         `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *LongRead) Reset() {
	*x = LongRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongRead) ProtoMessage() {}

func (x *LongRead) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongRead.ProtoReflect.Descriptor instead.
func (*LongRead) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{6}
}

func (x *LongRead) GetContent() *WebsiteContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *LongRead) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

type Measurement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height        int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Width         int64  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Unit          string `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	DimensionType string `protobuf:"bytes,4,opt,name=dimension_type,json=dimensionType,proto3" json:"dimension_type,omitempty"`
}

func (x *Measurement) Reset() {
	*x = Measurement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Measurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurement) ProtoMessage() {}

func (x *Measurement) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurement.ProtoReflect.Descriptor instead.
func (*Measurement) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{7}
}

func (x *Measurement) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Measurement) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Measurement) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Measurement) GetDimensionType() string {
	if x != nil {
		return x.DimensionType
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectNumber  string         `protobuf:"bytes,1,opt,name=object_number,json=objectNumber,proto3" json:"object_number,omitempty"`
	ObjectDate    string         `protobuf:"bytes,2,opt,name=object_date,json=objectDate,proto3" json:"object_date,omitempty"`
	Measurements  []*Measurement `protobuf:"bytes,3,rep,name=measurements,proto3" json:"measurements,omitempty"`
	Documentation string         `protobuf:"bytes,4,opt,name=documentation,proto3" json:"documentation,omitempty"`
	Association   string         `protobuf:"bytes,5,opt,name=association,proto3" json:"association,omitempty"`
	ObjectType    string         `protobuf:"bytes,6,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	Rights        string         `protobuf:"bytes,7,opt,name=rights,proto3" json:"rights,omitempty"`
	Theme         *Theme         `protobuf:"bytes,8,opt,name=theme,proto3" json:"theme,omitempty"`
	Creators      []*Person      `protobuf:"bytes,9,rep,name=creators,proto3" json:"creators,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{8}
}

func (x *Metadata) GetObjectNumber() string {
	if x != nil {
		return x.ObjectNumber
	}
	return ""
}

func (x *Metadata) GetObjectDate() string {
	if x != nil {
		return x.ObjectDate
	}
	return ""
}

func (x *Metadata) GetMeasurements() []*Measurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *Metadata) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *Metadata) GetAssociation() string {
	if x != nil {
		return x.Association
	}
	return ""
}

func (x *Metadata) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *Metadata) GetRights() string {
	if x != nil {
		return x.Rights
	}
	return ""
}

func (x *Metadata) GetTheme() *Theme {
	if x != nil {
		return x.Theme
	}
	return nil
}

func (x *Metadata) GetCreators() []*Person {
	if x != nil {
		return x.Creators
	}
	return nil
}

type Museum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Museum) Reset() {
	*x = Museum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Museum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Museum) ProtoMessage() {}

func (x *Museum) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Museum.ProtoReflect.Descriptor instead.
func (*Museum) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{9}
}

type ObjectRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Metadata  *Metadata     `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Relations *Relations    `protobuf:"bytes,3,opt,name=relations,proto3" json:"relations,omitempty"`
	Download  *DownloadLink `protobuf:"bytes,4,opt,name=download,proto3" json:"download,omitempty"`
	Id        string        `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ObjectRecord) Reset() {
	*x = ObjectRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRecord) ProtoMessage() {}

func (x *ObjectRecord) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRecord.ProtoReflect.Descriptor instead.
func (*ObjectRecord) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{10}
}

func (x *ObjectRecord) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ObjectRecord) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ObjectRecord) GetRelations() *Relations {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *ObjectRecord) GetDownload() *DownloadLink {
	if x != nil {
		return x.Download
	}
	return nil
}

func (x *ObjectRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Partner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Partner) Reset() {
	*x = Partner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Partner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partner) ProtoMessage() {}

func (x *Partner) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partner.ProtoReflect.Descriptor instead.
func (*Partner) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{11}
}

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{12}
}

type Relations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collections    []*Collection    `protobuf:"bytes,2,rep,name=collections,proto3" json:"collections,omitempty"`
	SubCollections []*SubCollection `protobuf:"bytes,3,rep,name=sub_collections,json=subCollections,proto3" json:"sub_collections,omitempty"`
	Themes         []*Theme         `protobuf:"bytes,4,rep,name=themes,proto3" json:"themes,omitempty"`
	Events         []*Event         `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	Museums        []*Museum        `protobuf:"bytes,6,rep,name=museums,proto3" json:"museums,omitempty"`
	Objects        []*ObjectRecord  `protobuf:"bytes,7,rep,name=objects,proto3" json:"objects,omitempty"`
	Persons        []*Person        `protobuf:"bytes,8,rep,name=persons,proto3" json:"persons,omitempty"`
	StoryCards     []*StoryCard     `protobuf:"bytes,9,rep,name=story_cards,json=storyCards,proto3" json:"story_cards,omitempty"`
	LongReads      []*LongRead      `protobuf:"bytes,10,rep,name=long_reads,json=longReads,proto3" json:"long_reads,omitempty"`
}

func (x *Relations) Reset() {
	*x = Relations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Relations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relations) ProtoMessage() {}

func (x *Relations) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relations.ProtoReflect.Descriptor instead.
func (*Relations) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{13}
}

func (x *Relations) GetCollections() []*Collection {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *Relations) GetSubCollections() []*SubCollection {
	if x != nil {
		return x.SubCollections
	}
	return nil
}

func (x *Relations) GetThemes() []*Theme {
	if x != nil {
		return x.Themes
	}
	return nil
}

func (x *Relations) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Relations) GetMuseums() []*Museum {
	if x != nil {
		return x.Museums
	}
	return nil
}

func (x *Relations) GetObjects() []*ObjectRecord {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *Relations) GetPersons() []*Person {
	if x != nil {
		return x.Persons
	}
	return nil
}

func (x *Relations) GetStoryCards() []*StoryCard {
	if x != nil {
		return x.StoryCards
	}
	return nil
}

func (x *Relations) GetLongReads() []*LongRead {
	if x != nil {
		return x.LongReads
	}
	return nil
}

type StoryCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content *WebsiteContent `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Header  *Header         `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *StoryCard) Reset() {
	*x = StoryCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoryCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryCard) ProtoMessage() {}

func (x *StoryCard) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryCard.ProtoReflect.Descriptor instead.
func (*StoryCard) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{14}
}

func (x *StoryCard) GetContent() *WebsiteContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *StoryCard) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

type StoryCardCollection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header      `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	StoryCard []*StoryCard `protobuf:"bytes,2,rep,name=story_card,json=storyCard,proto3" json:"story_card,omitempty"`
}

func (x *StoryCardCollection) Reset() {
	*x = StoryCardCollection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoryCardCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryCardCollection) ProtoMessage() {}

func (x *StoryCardCollection) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryCardCollection.ProtoReflect.Descriptor instead.
func (*StoryCardCollection) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{15}
}

func (x *StoryCardCollection) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *StoryCardCollection) GetStoryCard() []*StoryCard {
	if x != nil {
		return x.StoryCard
	}
	return nil
}

type SubCollection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubCollection) Reset() {
	*x = SubCollection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCollection) ProtoMessage() {}

func (x *SubCollection) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCollection.ProtoReflect.Descriptor instead.
func (*SubCollection) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{16}
}

type Theme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Theme) Reset() {
	*x = Theme{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Theme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Theme) ProtoMessage() {}

func (x *Theme) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Theme.ProtoReflect.Descriptor instead.
func (*Theme) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{17}
}

type Timeline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *Header   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Themes  []*Theme  `protobuf:"bytes,2,rep,name=themes,proto3" json:"themes,omitempty"`
	Persons []*Person `protobuf:"bytes,3,rep,name=persons,proto3" json:"persons,omitempty"`
	Events  []*Event  `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *Timeline) Reset() {
	*x = Timeline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeline) ProtoMessage() {}

func (x *Timeline) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeline.ProtoReflect.Descriptor instead.
func (*Timeline) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{18}
}

func (x *Timeline) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Timeline) GetThemes() []*Theme {
	if x != nil {
		return x.Themes
	}
	return nil
}

func (x *Timeline) GetPersons() []*Person {
	if x != nil {
		return x.Persons
	}
	return nil
}

func (x *Timeline) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type WebsiteContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Staticcontent string `protobuf:"bytes,1,opt,name=staticcontent,proto3" json:"staticcontent,omitempty"`
	// repeated Relations relations = 2;
	PublishDate string `protobuf:"bytes,3,opt,name=publish_date,json=publishDate,proto3" json:"publish_date,omitempty"`
}

func (x *WebsiteContent) Reset() {
	*x = WebsiteContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebsiteContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsiteContent) ProtoMessage() {}

func (x *WebsiteContent) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsiteContent.ProtoReflect.Descriptor instead.
func (*WebsiteContent) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{19}
}

func (x *WebsiteContent) GetStaticcontent() string {
	if x != nil {
		return x.Staticcontent
	}
	return ""
}

func (x *WebsiteContent) GetPublishDate() string {
	if x != nil {
		return x.PublishDate
	}
	return ""
}

var File_vhu_v1_definitions_proto protoreflect.FileDescriptor

var file_vhu_v1_definitions_proto_rawDesc = []byte{
	0x0a, 0x18, 0x76, 0x68, 0x75, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x76, 0x68, 0x75, 0x2e,
	0x76, 0x31, 0x22, 0x0c, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x33, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12,
	0x24, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x52, 0x0a, 0x0c, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x69, 0x67, 0x68, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x22, 0x81, 0x01, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12,
	0x25, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x22, 0x4b, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x69, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x64, 0x0a, 0x08, 0x4c, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x61, 0x64, 0x12,
	0x30, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65, 0x62, 0x73, 0x69, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x76, 0x0a, 0x0b, 0x4d, 0x65, 0x61,
	0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x69,
	0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x22, 0xdb, 0x02, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x23,
	0x0a, 0x0d, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x44, 0x61, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76, 0x68, 0x75,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x0c, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x24, 0x0a,
	0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x73, 0x73, 0x6f, 0x63, 0x69,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x23,
	0x0a, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x05, 0x74, 0x68,
	0x65, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18,
	0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x22,
	0x08, 0x0a, 0x06, 0x4d, 0x75, 0x73, 0x65, 0x75, 0x6d, 0x22, 0xd7, 0x01, 0x0a, 0x0c, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x68, 0x75,
	0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x2f, 0x0a, 0x09, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x09, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x30, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x09, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x22, 0x08,
	0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x22, 0xb8, 0x03, 0x0a, 0x09, 0x52, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x34, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x68,
	0x75, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0b, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3e, 0x0a, 0x0f,
	0x73, 0x75, 0x62, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x75, 0x62, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x73, 0x75,
	0x62, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x06,
	0x74, 0x68, 0x65, 0x6d, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76,
	0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x06, 0x74, 0x68, 0x65,
	0x6d, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x75,
	0x73, 0x65, 0x75, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x68,
	0x75, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x75, 0x73, 0x65, 0x75, 0x6d, 0x52, 0x07, 0x6d, 0x75, 0x73,
	0x65, 0x75, 0x6d, 0x73, 0x12, 0x2e, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x18,
	0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x12, 0x32,
	0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x79, 0x43, 0x61, 0x72, 0x64, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x61, 0x72,
	0x64, 0x73, 0x12, 0x2f, 0x0a, 0x0a, 0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x73,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x61, 0x64, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x52, 0x65,
	0x61, 0x64, 0x73, 0x22, 0x65, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x61, 0x72, 0x64,
	0x12, 0x30, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65, 0x62, 0x73, 0x69,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x6f, 0x0a, 0x13, 0x53, 0x74,
	0x6f, 0x72, 0x79, 0x43, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x0a, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x61, 0x72, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x53,
	0x75, 0x62, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x07, 0x0a, 0x05,
	0x54, 0x68, 0x65, 0x6d, 0x65, 0x22, 0xaa, 0x01, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x06, 0x74, 0x68,
	0x65, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x68, 0x75,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x06, 0x74, 0x68, 0x65, 0x6d, 0x65,
	0x73, 0x12, 0x28, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x68,
	0x75, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0x59, 0x0a, 0x0e, 0x57, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x63, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x44, 0x61, 0x74, 0x65, 0x42, 0x1c, 0x5a,
	0x07, 0x70, 0x6f, 0x63, 0x2f, 0x76, 0x68, 0x75, 0xca, 0x02, 0x10, 0x41, 0x70, 0x70, 0x5c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5c, 0x56, 0x48, 0x55, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_vhu_v1_definitions_proto_rawDescOnce sync.Once
	file_vhu_v1_definitions_proto_rawDescData = file_vhu_v1_definitions_proto_rawDesc
)

func file_vhu_v1_definitions_proto_rawDescGZIP() []byte {
	file_vhu_v1_definitions_proto_rawDescOnce.Do(func() {
		file_vhu_v1_definitions_proto_rawDescData = protoimpl.X.CompressGZIP(file_vhu_v1_definitions_proto_rawDescData)
	})
	return file_vhu_v1_definitions_proto_rawDescData
}

var file_vhu_v1_definitions_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_vhu_v1_definitions_proto_goTypes = []interface{}{
	(*Collection)(nil),          // 0: vhu.v1.Collection
	(*ContentPage)(nil),         // 1: vhu.v1.ContentPage
	(*DownloadLink)(nil),        // 2: vhu.v1.DownloadLink
	(*Event)(nil),               // 3: vhu.v1.Event
	(*Header)(nil),              // 4: vhu.v1.Header
	(*Image)(nil),               // 5: vhu.v1.Image
	(*LongRead)(nil),            // 6: vhu.v1.LongRead
	(*Measurement)(nil),         // 7: vhu.v1.Measurement
	(*Metadata)(nil),            // 8: vhu.v1.Metadata
	(*Museum)(nil),              // 9: vhu.v1.Museum
	(*ObjectRecord)(nil),        // 10: vhu.v1.ObjectRecord
	(*Partner)(nil),             // 11: vhu.v1.Partner
	(*Person)(nil),              // 12: vhu.v1.Person
	(*Relations)(nil),           // 13: vhu.v1.Relations
	(*StoryCard)(nil),           // 14: vhu.v1.StoryCard
	(*StoryCardCollection)(nil), // 15: vhu.v1.StoryCardCollection
	(*SubCollection)(nil),       // 16: vhu.v1.SubCollection
	(*Theme)(nil),               // 17: vhu.v1.Theme
	(*Timeline)(nil),            // 18: vhu.v1.Timeline
	(*WebsiteContent)(nil),      // 19: vhu.v1.WebsiteContent
}
var file_vhu_v1_definitions_proto_depIdxs = []int32{
	5,  // 0: vhu.v1.Header.images:type_name -> vhu.v1.Image
	19, // 1: vhu.v1.LongRead.content:type_name -> vhu.v1.WebsiteContent
	4,  // 2: vhu.v1.LongRead.header:type_name -> vhu.v1.Header
	7,  // 3: vhu.v1.Metadata.measurements:type_name -> vhu.v1.Measurement
	17, // 4: vhu.v1.Metadata.theme:type_name -> vhu.v1.Theme
	12, // 5: vhu.v1.Metadata.creators:type_name -> vhu.v1.Person
	4,  // 6: vhu.v1.ObjectRecord.header:type_name -> vhu.v1.Header
	8,  // 7: vhu.v1.ObjectRecord.metadata:type_name -> vhu.v1.Metadata
	13, // 8: vhu.v1.ObjectRecord.relations:type_name -> vhu.v1.Relations
	2,  // 9: vhu.v1.ObjectRecord.download:type_name -> vhu.v1.DownloadLink
	0,  // 10: vhu.v1.Relations.collections:type_name -> vhu.v1.Collection
	16, // 11: vhu.v1.Relations.sub_collections:type_name -> vhu.v1.SubCollection
	17, // 12: vhu.v1.Relations.themes:type_name -> vhu.v1.Theme
	3,  // 13: vhu.v1.Relations.events:type_name -> vhu.v1.Event
	9,  // 14: vhu.v1.Relations.museums:type_name -> vhu.v1.Museum
	10, // 15: vhu.v1.Relations.objects:type_name -> vhu.v1.ObjectRecord
	12, // 16: vhu.v1.Relations.persons:type_name -> vhu.v1.Person
	14, // 17: vhu.v1.Relations.story_cards:type_name -> vhu.v1.StoryCard
	6,  // 18: vhu.v1.Relations.long_reads:type_name -> vhu.v1.LongRead
	19, // 19: vhu.v1.StoryCard.content:type_name -> vhu.v1.WebsiteContent
	4,  // 20: vhu.v1.StoryCard.header:type_name -> vhu.v1.Header
	4,  // 21: vhu.v1.StoryCardCollection.header:type_name -> vhu.v1.Header
	14, // 22: vhu.v1.StoryCardCollection.story_card:type_name -> vhu.v1.StoryCard
	4,  // 23: vhu.v1.Timeline.header:type_name -> vhu.v1.Header
	17, // 24: vhu.v1.Timeline.themes:type_name -> vhu.v1.Theme
	12, // 25: vhu.v1.Timeline.persons:type_name -> vhu.v1.Person
	3,  // 26: vhu.v1.Timeline.events:type_name -> vhu.v1.Event
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_vhu_v1_definitions_proto_init() }
func file_vhu_v1_definitions_proto_init() {
	if File_vhu_v1_definitions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vhu_v1_definitions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Collection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Measurement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Museum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Partner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Relations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoryCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoryCardCollection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubCollection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Theme); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Timeline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebsiteContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vhu_v1_definitions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vhu_v1_definitions_proto_goTypes,
		DependencyIndexes: file_vhu_v1_definitions_proto_depIdxs,
		MessageInfos:      file_vhu_v1_definitions_proto_msgTypes,
	}.Build()
	File_vhu_v1_definitions_proto = out.File
	file_vhu_v1_definitions_proto_rawDesc = nil
	file_vhu_v1_definitions_proto_goTypes = nil
	file_vhu_v1_definitions_proto_depIdxs = nil
}
