// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: vhu/v1/definitions.proto

package vhu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Summary     string   `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Images      []*Image `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	Id          string   `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`   // objectnumber
	Uri         string   `protobuf:"bytes,6,opt,name=uri,proto3" json:"uri,omitempty"` // RDF URI
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Header) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Header) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Header) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Header) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Header) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri     string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Rights  string `protobuf:"bytes,2,opt,name=rights,proto3" json:"rights,omitempty"`
	Caption string `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{1}
}

func (x *Image) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Image) GetRights() string {
	if x != nil {
		return x.Rights
	}
	return ""
}

func (x *Image) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

type Timeline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Events []*Event `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *Timeline) Reset() {
	*x = Timeline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeline) ProtoMessage() {}

func (x *Timeline) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeline.ProtoReflect.Descriptor instead.
func (*Timeline) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{2}
}

func (x *Timeline) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Timeline) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	StartDate string              `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate   string              `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Period    string              `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	Objects   []*MuseumObjectInfo `protobuf:"bytes,5,rep,name=objects,proto3" json:"objects,omitempty"`
	IsGroup   bool                `protobuf:"varint,6,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`
	Year      string              `protobuf:"bytes,7,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Event) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Event) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Event) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *Event) GetObjects() []*MuseumObjectInfo {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *Event) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

func (x *Event) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

type MuseumObjectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title        string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Image        string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Id           string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Uri          string `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	ObjectNumber string `protobuf:"bytes,5,opt,name=object_number,json=objectNumber,proto3" json:"object_number,omitempty"`
	MuseumName   string `protobuf:"bytes,6,opt,name=museum_name,json=museumName,proto3" json:"museum_name,omitempty"`
	ConceptLabel string `protobuf:"bytes,7,opt,name=concept_label,json=conceptLabel,proto3" json:"concept_label,omitempty"`
}

func (x *MuseumObjectInfo) Reset() {
	*x = MuseumObjectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MuseumObjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuseumObjectInfo) ProtoMessage() {}

func (x *MuseumObjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuseumObjectInfo.ProtoReflect.Descriptor instead.
func (*MuseumObjectInfo) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{4}
}

func (x *MuseumObjectInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MuseumObjectInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MuseumObjectInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MuseumObjectInfo) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *MuseumObjectInfo) GetObjectNumber() string {
	if x != nil {
		return x.ObjectNumber
	}
	return ""
}

func (x *MuseumObjectInfo) GetMuseumName() string {
	if x != nil {
		return x.MuseumName
	}
	return ""
}

func (x *MuseumObjectInfo) GetConceptLabel() string {
	if x != nil {
		return x.ConceptLabel
	}
	return ""
}

type MuseumObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header         *Header             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Metadata       *Metadata           `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Concepts       []*ThesaurusConcept `protobuf:"bytes,3,rep,name=concepts,proto3" json:"concepts,omitempty"` // skos:relatedMatch via thesaurus link
	RelatedObjects []*MuseumObject     `protobuf:"bytes,4,rep,name=related_objects,json=relatedObjects,proto3" json:"related_objects,omitempty"`
	LinkInfo       *ObjLinkInfo        `protobuf:"bytes,5,opt,name=link_info,json=linkInfo,proto3" json:"link_info,omitempty"`
}

func (x *MuseumObject) Reset() {
	*x = MuseumObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MuseumObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuseumObject) ProtoMessage() {}

func (x *MuseumObject) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuseumObject.ProtoReflect.Descriptor instead.
func (*MuseumObject) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{5}
}

func (x *MuseumObject) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MuseumObject) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MuseumObject) GetConcepts() []*ThesaurusConcept {
	if x != nil {
		return x.Concepts
	}
	return nil
}

func (x *MuseumObject) GetRelatedObjects() []*MuseumObject {
	if x != nil {
		return x.RelatedObjects
	}
	return nil
}

func (x *MuseumObject) GetLinkInfo() *ObjLinkInfo {
	if x != nil {
		return x.LinkInfo
	}
	return nil
}

type ObjLinkInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MuseumName   string `protobuf:"bytes,1,opt,name=museum_name,json=museumName,proto3" json:"museum_name,omitempty"`
	ObjectNumber string `protobuf:"bytes,2,opt,name=object_number,json=objectNumber,proto3" json:"object_number,omitempty"`
	ObjectName   string `protobuf:"bytes,3,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	DcnUri       string `protobuf:"bytes,4,opt,name=dcn_uri,json=dcnUri,proto3" json:"dcn_uri,omitempty"`
}

func (x *ObjLinkInfo) Reset() {
	*x = ObjLinkInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjLinkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjLinkInfo) ProtoMessage() {}

func (x *ObjLinkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjLinkInfo.ProtoReflect.Descriptor instead.
func (*ObjLinkInfo) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{6}
}

func (x *ObjLinkInfo) GetMuseumName() string {
	if x != nil {
		return x.MuseumName
	}
	return ""
}

func (x *ObjLinkInfo) GetObjectNumber() string {
	if x != nil {
		return x.ObjectNumber
	}
	return ""
}

func (x *ObjLinkInfo) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *ObjLinkInfo) GetDcnUri() string {
	if x != nil {
		return x.DcnUri
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectNumber  string         `protobuf:"bytes,1,opt,name=object_number,json=objectNumber,proto3" json:"object_number,omitempty"`
	ObjectDate    string         `protobuf:"bytes,2,opt,name=object_date,json=objectDate,proto3" json:"object_date,omitempty"`
	Measurements  []*Measurement `protobuf:"bytes,3,rep,name=measurements,proto3" json:"measurements,omitempty"`
	Documentation string         `protobuf:"bytes,4,opt,name=documentation,proto3" json:"documentation,omitempty"`
	Association   string         `protobuf:"bytes,5,opt,name=association,proto3" json:"association,omitempty"`
	ObjectType    []string       `protobuf:"bytes,6,rep,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	Rights        string         `protobuf:"bytes,7,opt,name=rights,proto3" json:"rights,omitempty"`
	Creators      []string       `protobuf:"bytes,9,rep,name=creators,proto3" json:"creators,omitempty"`
	Subject       []string       `protobuf:"bytes,10,rep,name=subject,proto3" json:"subject,omitempty"`
	Dimensions    []string       `protobuf:"bytes,12,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	Material      []string       `protobuf:"bytes,13,rep,name=material,proto3" json:"material,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{7}
}

func (x *Metadata) GetObjectNumber() string {
	if x != nil {
		return x.ObjectNumber
	}
	return ""
}

func (x *Metadata) GetObjectDate() string {
	if x != nil {
		return x.ObjectDate
	}
	return ""
}

func (x *Metadata) GetMeasurements() []*Measurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *Metadata) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *Metadata) GetAssociation() string {
	if x != nil {
		return x.Association
	}
	return ""
}

func (x *Metadata) GetObjectType() []string {
	if x != nil {
		return x.ObjectType
	}
	return nil
}

func (x *Metadata) GetRights() string {
	if x != nil {
		return x.Rights
	}
	return ""
}

func (x *Metadata) GetCreators() []string {
	if x != nil {
		return x.Creators
	}
	return nil
}

func (x *Metadata) GetSubject() []string {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Metadata) GetDimensions() []string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *Metadata) GetMaterial() []string {
	if x != nil {
		return x.Material
	}
	return nil
}

type Measurement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height        int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Width         int64  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Unit          string `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	DimensionType string `protobuf:"bytes,4,opt,name=dimension_type,json=dimensionType,proto3" json:"dimension_type,omitempty"`
}

func (x *Measurement) Reset() {
	*x = Measurement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Measurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurement) ProtoMessage() {}

func (x *Measurement) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurement.ProtoReflect.Descriptor instead.
func (*Measurement) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{8}
}

func (x *Measurement) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Measurement) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Measurement) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Measurement) GetDimensionType() string {
	if x != nil {
		return x.DimensionType
	}
	return ""
}

type ThesaurusConcept struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // STT URI
	PrefLabel  string `protobuf:"bytes,2,opt,name=pref_label,json=prefLabel,proto3" json:"pref_label,omitempty"`
	ScopeNotes string `protobuf:"bytes,3,opt,name=scope_notes,json=scopeNotes,proto3" json:"scope_notes,omitempty"`
}

func (x *ThesaurusConcept) Reset() {
	*x = ThesaurusConcept{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vhu_v1_definitions_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThesaurusConcept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThesaurusConcept) ProtoMessage() {}

func (x *ThesaurusConcept) ProtoReflect() protoreflect.Message {
	mi := &file_vhu_v1_definitions_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThesaurusConcept.ProtoReflect.Descriptor instead.
func (*ThesaurusConcept) Descriptor() ([]byte, []int) {
	return file_vhu_v1_definitions_proto_rawDescGZIP(), []int{9}
}

func (x *ThesaurusConcept) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThesaurusConcept) GetPrefLabel() string {
	if x != nil {
		return x.PrefLabel
	}
	return ""
}

func (x *ThesaurusConcept) GetScopeNotes() string {
	if x != nil {
		return x.ScopeNotes
	}
	return ""
}

var File_vhu_v1_definitions_proto protoreflect.FileDescriptor

var file_vhu_v1_definitions_proto_rawDesc = []byte{
	0x0a, 0x18, 0x76, 0x68, 0x75, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x76, 0x68, 0x75, 0x2e,
	0x76, 0x31, 0x22, 0xa3, 0x01, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12,
	0x25, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x22, 0x4b, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x59, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x06, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x68, 0x75, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0xe4, 0x01, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x68, 0x75,
	0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x12, 0x32, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x75, 0x73, 0x65, 0x75, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22, 0xcb, 0x01, 0x0a, 0x10, 0x4d, 0x75, 0x73, 0x65,
	0x75, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x1f, 0x0a, 0x0b, 0x6d, 0x75, 0x73, 0x65, 0x75, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x75, 0x73, 0x65, 0x75, 0x6d, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x5f, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x8b, 0x02, 0x0a, 0x0c, 0x4d, 0x75, 0x73, 0x65, 0x75, 0x6d,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2c,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x08,
	0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x68, 0x65, 0x73, 0x61, 0x75, 0x72, 0x75,
	0x73, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70,
	0x74, 0x73, 0x12, 0x3d, 0x0a, 0x0f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x68,
	0x75, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x75, 0x73, 0x65, 0x75, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x0e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x12, 0x30, 0x0a, 0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76, 0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62,
	0x6a, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x4f, 0x62, 0x6a, 0x4c, 0x69, 0x6e, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x75, 0x73, 0x65, 0x75, 0x6d, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x75, 0x73, 0x65, 0x75, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x63,
	0x6e, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x63, 0x6e,
	0x55, 0x72, 0x69, 0x22, 0xfc, 0x02, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76,
	0x68, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x0c, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x24, 0x0a, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x73, 0x73, 0x6f,
	0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x09, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x69, 0x6d, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x22, 0x76, 0x0a, 0x0b, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x6e, 0x69, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x69, 0x6d,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x62, 0x0a, 0x10, 0x54, 0x68,
	0x65, 0x73, 0x61, 0x75, 0x72, 0x75, 0x73, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x72, 0x65, 0x66, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x65, 0x66, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x42, 0x1c,
	0x5a, 0x07, 0x70, 0x6f, 0x63, 0x2f, 0x76, 0x68, 0x75, 0xca, 0x02, 0x10, 0x41, 0x70, 0x70, 0x5c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5c, 0x56, 0x48, 0x55, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vhu_v1_definitions_proto_rawDescOnce sync.Once
	file_vhu_v1_definitions_proto_rawDescData = file_vhu_v1_definitions_proto_rawDesc
)

func file_vhu_v1_definitions_proto_rawDescGZIP() []byte {
	file_vhu_v1_definitions_proto_rawDescOnce.Do(func() {
		file_vhu_v1_definitions_proto_rawDescData = protoimpl.X.CompressGZIP(file_vhu_v1_definitions_proto_rawDescData)
	})
	return file_vhu_v1_definitions_proto_rawDescData
}

var file_vhu_v1_definitions_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_vhu_v1_definitions_proto_goTypes = []interface{}{
	(*Header)(nil),           // 0: vhu.v1.Header
	(*Image)(nil),            // 1: vhu.v1.Image
	(*Timeline)(nil),         // 2: vhu.v1.Timeline
	(*Event)(nil),            // 3: vhu.v1.Event
	(*MuseumObjectInfo)(nil), // 4: vhu.v1.MuseumObjectInfo
	(*MuseumObject)(nil),     // 5: vhu.v1.MuseumObject
	(*ObjLinkInfo)(nil),      // 6: vhu.v1.ObjLinkInfo
	(*Metadata)(nil),         // 7: vhu.v1.Metadata
	(*Measurement)(nil),      // 8: vhu.v1.Measurement
	(*ThesaurusConcept)(nil), // 9: vhu.v1.ThesaurusConcept
}
var file_vhu_v1_definitions_proto_depIdxs = []int32{
	1,  // 0: vhu.v1.Header.images:type_name -> vhu.v1.Image
	0,  // 1: vhu.v1.Timeline.header:type_name -> vhu.v1.Header
	3,  // 2: vhu.v1.Timeline.events:type_name -> vhu.v1.Event
	0,  // 3: vhu.v1.Event.header:type_name -> vhu.v1.Header
	4,  // 4: vhu.v1.Event.objects:type_name -> vhu.v1.MuseumObjectInfo
	0,  // 5: vhu.v1.MuseumObject.header:type_name -> vhu.v1.Header
	7,  // 6: vhu.v1.MuseumObject.metadata:type_name -> vhu.v1.Metadata
	9,  // 7: vhu.v1.MuseumObject.concepts:type_name -> vhu.v1.ThesaurusConcept
	5,  // 8: vhu.v1.MuseumObject.related_objects:type_name -> vhu.v1.MuseumObject
	6,  // 9: vhu.v1.MuseumObject.link_info:type_name -> vhu.v1.ObjLinkInfo
	8,  // 10: vhu.v1.Metadata.measurements:type_name -> vhu.v1.Measurement
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_vhu_v1_definitions_proto_init() }
func file_vhu_v1_definitions_proto_init() {
	if File_vhu_v1_definitions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vhu_v1_definitions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Timeline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MuseumObjectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MuseumObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjLinkInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Measurement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vhu_v1_definitions_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThesaurusConcept); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vhu_v1_definitions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vhu_v1_definitions_proto_goTypes,
		DependencyIndexes: file_vhu_v1_definitions_proto_depIdxs,
		MessageInfos:      file_vhu_v1_definitions_proto_msgTypes,
	}.Build()
	File_vhu_v1_definitions_proto = out.File
	file_vhu_v1_definitions_proto_rawDesc = nil
	file_vhu_v1_definitions_proto_goTypes = nil
	file_vhu_v1_definitions_proto_depIdxs = nil
}
