<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scifind/v1/services.proto

namespace Scifind\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scifind.v1.GetTimelineResponse</code>
 */
class GetTimelineResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.scifind.v1.Timeline object = 1 [json_name = "object"];</code>
     */
    protected $object = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Scifind\V1\Timeline $object
     * }
     */
    public function __construct($data = NULL) {
        \Scifind\V1\GPBMetadata\Services::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.scifind.v1.Timeline object = 1 [json_name = "object"];</code>
     * @return \Scifind\V1\Timeline|null
     */
    public function getObject()
    {
        return $this->object;
    }

    public function hasObject()
    {
        return isset($this->object);
    }

    public function clearObject()
    {
        unset($this->object);
    }

    /**
     * Generated from protobuf field <code>.scifind.v1.Timeline object = 1 [json_name = "object"];</code>
     * @param \Scifind\V1\Timeline $var
     * @return $this
     */
    public function setObject($var)
    {
        GPBUtil::checkMessage($var, \Scifind\V1\Timeline::class);
        $this->object = $var;

        return $this;
    }

}

