<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scifind/v1/definitions.proto

namespace Scifind\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scifind.v1.Measurement</code>
 */
class Measurement extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 height = 1 [json_name = "height"];</code>
     */
    protected $height = 0;
    /**
     * Generated from protobuf field <code>int64 width = 2 [json_name = "width"];</code>
     */
    protected $width = 0;
    /**
     * Generated from protobuf field <code>string unit = 3 [json_name = "unit"];</code>
     */
    protected $unit = '';
    /**
     * Generated from protobuf field <code>string dimension_type = 4 [json_name = "dimensionType"];</code>
     */
    protected $dimension_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $height
     *     @type int|string $width
     *     @type string $unit
     *     @type string $dimension_type
     * }
     */
    public function __construct($data = NULL) {
        \Scifind\V1\GPBMetadata\Definitions::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 height = 1 [json_name = "height"];</code>
     * @return int|string
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int64 height = 1 [json_name = "height"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 width = 2 [json_name = "width"];</code>
     * @return int|string
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Generated from protobuf field <code>int64 width = 2 [json_name = "width"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkInt64($var);
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unit = 3 [json_name = "unit"];</code>
     * @return string
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * Generated from protobuf field <code>string unit = 3 [json_name = "unit"];</code>
     * @param string $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkString($var, True);
        $this->unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dimension_type = 4 [json_name = "dimensionType"];</code>
     * @return string
     */
    public function getDimensionType()
    {
        return $this->dimension_type;
    }

    /**
     * Generated from protobuf field <code>string dimension_type = 4 [json_name = "dimensionType"];</code>
     * @param string $var
     * @return $this
     */
    public function setDimensionType($var)
    {
        GPBUtil::checkString($var, True);
        $this->dimension_type = $var;

        return $this;
    }

}

