<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scifind/v1/definitions.proto

namespace Scifind\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scifind.v1.StoryCard</code>
 */
class StoryCard extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.scifind.v1.WebsiteContent content = 1 [json_name = "content"];</code>
     */
    protected $content = null;
    /**
     * Generated from protobuf field <code>.scifind.v1.Header header = 2 [json_name = "header"];</code>
     */
    protected $header = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Scifind\V1\WebsiteContent $content
     *     @type \Scifind\V1\Header $header
     * }
     */
    public function __construct($data = NULL) {
        \Scifind\V1\GPBMetadata\Definitions::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.scifind.v1.WebsiteContent content = 1 [json_name = "content"];</code>
     * @return \Scifind\V1\WebsiteContent|null
     */
    public function getContent()
    {
        return $this->content;
    }

    public function hasContent()
    {
        return isset($this->content);
    }

    public function clearContent()
    {
        unset($this->content);
    }

    /**
     * Generated from protobuf field <code>.scifind.v1.WebsiteContent content = 1 [json_name = "content"];</code>
     * @param \Scifind\V1\WebsiteContent $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkMessage($var, \Scifind\V1\WebsiteContent::class);
        $this->content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.scifind.v1.Header header = 2 [json_name = "header"];</code>
     * @return \Scifind\V1\Header|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.scifind.v1.Header header = 2 [json_name = "header"];</code>
     * @param \Scifind\V1\Header $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Scifind\V1\Header::class);
        $this->header = $var;

        return $this;
    }

}

