<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scifind/v1/definitions.proto

namespace Scifind\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scifind.v1.Timeline</code>
 */
class Timeline extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.scifind.v1.Header header = 1 [json_name = "header"];</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>repeated .scifind.v1.Theme themes = 2 [json_name = "themes"];</code>
     */
    private $themes;
    /**
     * Generated from protobuf field <code>repeated .scifind.v1.Person persons = 3 [json_name = "persons"];</code>
     */
    private $persons;
    /**
     * Generated from protobuf field <code>repeated .scifind.v1.Event events = 4 [json_name = "events"];</code>
     */
    private $events;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Scifind\V1\Header $header
     *     @type array<\Scifind\V1\Theme>|\Google\Protobuf\Internal\RepeatedField $themes
     *     @type array<\Scifind\V1\Person>|\Google\Protobuf\Internal\RepeatedField $persons
     *     @type array<\Scifind\V1\Event>|\Google\Protobuf\Internal\RepeatedField $events
     * }
     */
    public function __construct($data = NULL) {
        \Scifind\V1\GPBMetadata\Definitions::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.scifind.v1.Header header = 1 [json_name = "header"];</code>
     * @return \Scifind\V1\Header|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.scifind.v1.Header header = 1 [json_name = "header"];</code>
     * @param \Scifind\V1\Header $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Scifind\V1\Header::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .scifind.v1.Theme themes = 2 [json_name = "themes"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getThemes()
    {
        return $this->themes;
    }

    /**
     * Generated from protobuf field <code>repeated .scifind.v1.Theme themes = 2 [json_name = "themes"];</code>
     * @param array<\Scifind\V1\Theme>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setThemes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Scifind\V1\Theme::class);
        $this->themes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .scifind.v1.Person persons = 3 [json_name = "persons"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPersons()
    {
        return $this->persons;
    }

    /**
     * Generated from protobuf field <code>repeated .scifind.v1.Person persons = 3 [json_name = "persons"];</code>
     * @param array<\Scifind\V1\Person>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPersons($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Scifind\V1\Person::class);
        $this->persons = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .scifind.v1.Event events = 4 [json_name = "events"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .scifind.v1.Event events = 4 [json_name = "events"];</code>
     * @param array<\Scifind\V1\Event>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Scifind\V1\Event::class);
        $this->events = $arr;

        return $this;
    }

}

