<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scifind/v1/definitions.proto

namespace App\Services\Scifind\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scifind.v1.WebsiteContent</code>
 */
class WebsiteContent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string staticcontent = 1 [json_name = "staticcontent"];</code>
     */
    protected $staticcontent = '';
    /**
     * repeated Relations relations = 2; 
     *
     * Generated from protobuf field <code>string publish_date = 3 [json_name = "publishDate"];</code>
     */
    protected $publish_date = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $staticcontent
     *     @type string $publish_date
     *           repeated Relations relations = 2; 
     * }
     */
    public function __construct($data = NULL) {
        \Scifind\V1\GPBMetadata\Definitions::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string staticcontent = 1 [json_name = "staticcontent"];</code>
     * @return string
     */
    public function getStaticcontent()
    {
        return $this->staticcontent;
    }

    /**
     * Generated from protobuf field <code>string staticcontent = 1 [json_name = "staticcontent"];</code>
     * @param string $var
     * @return $this
     */
    public function setStaticcontent($var)
    {
        GPBUtil::checkString($var, True);
        $this->staticcontent = $var;

        return $this;
    }

    /**
     * repeated Relations relations = 2; 
     *
     * Generated from protobuf field <code>string publish_date = 3 [json_name = "publishDate"];</code>
     * @return string
     */
    public function getPublishDate()
    {
        return $this->publish_date;
    }

    /**
     * repeated Relations relations = 2; 
     *
     * Generated from protobuf field <code>string publish_date = 3 [json_name = "publishDate"];</code>
     * @param string $var
     * @return $this
     */
    public function setPublishDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->publish_date = $var;

        return $this;
    }

}

