<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scifind/v1/services.proto

namespace Scifind\V1\GPBMetadata;

class Services
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Scifind\V1\GPBMetadata\Definitions::initOnce();
        $pool->internalAddGeneratedFile(
            '
›
scifind/v1/services.proto
scifind.v1""
GetObjectRequest
id (	Rid"?
GetObjectResponse*
object (2.scifind.v1.ObjectRobject"$
GetTimelineRequest
id (	Rid"C
GetTimelineResponse,
object (2.scifind.v1.TimelineRobject2Y
ObjectServiceH
	GetObject.scifind.v1.GetObjectRequest.scifind.v1.GetObjectResponse2a
TimelineServiceN
GetTimeline.scifind.v1.GetTimelineRequest.scifind.v1.GetTimelineResponseBù
com.scifind.v1BServicesProtoPZ3github.com/delving/scifind/gen/scifind/v1;scifindv1¢SXX™
Scifind.V1 
Scifind\\V1‚Scifind\\V1\\GPBMetadataÍScifind::V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

